service: pickem

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-plugin-warmup
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${env:stage, 'dev'}
  region: us-east-1
  environment:
    PARTICIPANTS_TABLE: ${self:service}-${opt:stage, self:provider.stage}-participants
    GAMES_TABLE: ${self:service}-${opt:stage, self:provider.stage}-games
    PICKS_TABLE: ${self:service}-${opt:stage, self:provider.stage}-picks
    USER_POOL_ID: ${env:userPoolId}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - cognito-idp:ListUsers
        - lambda:InvokeFunction
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
      Resource: "*"

functions:
  testerFunction:
    handler: app/private/tester.tester
    description: Used for testing functions
  getStandings:
    warmup: ${env:preWarm}
    prewarm: ${env:preWarm}
    handler: app/public/standings.getStandings
    description: Regular Season Standings
    events:
      - http:
          path: standings
          method: get
          cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - jwtheader
              allowCredentials: true
  getStandingsByWeek:
    warmup: ${env:preWarm}
    prewarm: ${env:preWarm}
    handler: app/public/standings.getStandingsByWeek
    description: Standings by Week
    events:
      - http:
          path: standings/{weekNumber}
          method: get
          cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - jwtheader
              allowCredentials: true
  getPicksOneWeekAllPlayers:
    warmup: ${env:preWarm}
    prewarm: ${env:preWarm}
    handler: app/public/picks.getPicksByWeek
    description: All Players Picks, One Week
    events:
      - http:
          path: picks/all/{weekNumber}
          method: get
          cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - jwtheader
              allowCredentials: true
  getPicksOneWeekOnePlayer:
    warmup: ${env:preWarm}
    prewarm: ${env:preWarm}
    handler: app/public/picks.getPicksByWeekByPlayer
    description: One Player Picks, One Week
    events:
      - http:
          path: picks/{weekNumber}
          method: get
          cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - jwtheader
              allowCredentials: true
  getPicksAllWeeksOnePlayer:
    warmup: ${env:preWarm}
    prewarm: ${env:preWarm}
    handler: app/public/picks.getPicksByPlayer
    description: One Player Picks, All Weeks
    events:
      - http:
          path: picks
          method: get
          cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - jwtheader
              allowCredentials: true
  setPick:
    warmup: ${env:preWarm}
    prewarm: ${env:preWarm}
    handler: app/public/picks.updatePick
    description: Set pick for one week
    events:
      - http:
          path: picks
          method: put
          cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - jwtheader
              allowCredentials: true
  createGame:
    warmup: ${env:preWarm}
    prewarm: ${env:preWarm}
    handler: app/public/games.createGame
    description: Create Game
    events:
      - http:
          path: games/create
          method: post
          cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - jwtheader
              allowCredentials: true
  getGamesByWeek:
    warmup: ${env:preWarm}
    prewarm: ${env:preWarm}
    handler: app/public/games.getGamesByWeek
    description: List the Number of Games per Week
    events:
      - http:
          path: games
          method: get
          cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - jwtheader
              allowCredentials: true
  updateGame:
    warmup: ${env:preWarm}
    prewarm: ${env:preWarm}
    handler: app/public/games.updateGame
    description: Update Game
    events:
      - http:
          path: games/update/{gameId}
          method: put
          cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - jwtheader
              allowCredentials: true
  setWinner:
    warmup: ${env:preWarm}
    prewarm: ${env:preWarm}
    handler: app/public/games.setWinner
    description: Set Game Winner
    events:
      - http:
          path: games/setWinner/{gameId}
          method: put
          cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - jwtheader
              allowCredentials: true
  getPayoutStructure:
    warmup: ${env:preWarm}
    prewarm: ${env:preWarm}
    handler: app/public/rules.getPayoutStructure
    description: Get Payout Structure
    events:
      - http:
          path: rules/payoutStructure
          method: get
          cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - jwtheader
              allowCredentials: true
  getCurrentParticipantStatus:
    warmup: ${env:preWarm}
    prewarm: ${env:preWarm}
    handler: app/public/users.getSingleParticipant
    description: Get Info on Current Participant
    events:
      - http:
          path: user
          method: get
          cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - jwtheader
              allowCredentials: true
  getAllParticipants:
    warmup: ${env:preWarm}
    prewarm: ${env:preWarm}
    handler: app/public/users.getAllParticipants
    description: Get All Participants
    events:
      - http:
          path: user/all
          method: get
          cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - jwtheader
              allowCredentials: true
  updateParticipant:
    warmup: ${env:preWarm}
    prewarm: ${env:preWarm}
    handler: app/public/users.updateParticipant
    description: Update a Participant
    events:
      - http:
          path: user/{userId}
          method: put
          cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - jwtheader
              allowCredentials: true
          
resources:
  Resources:
    ParticipantsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "participantId"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "participantId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.PARTICIPANTS_TABLE}
    GamesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "gameId"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "gameId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.GAMES_TABLE}
    PicksDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "pickId"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "pickId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.PICKS_TABLE}